jobenfance:
  adapter: mysql2
  host: localhost
  username: root
  password: admin
  pool: 10
  reconnect: false
  database: axagenda-jobenfance
  # socket: /var/run/mysqld/mysqld.sock

jobdependance:
  adapter: mysql2
  host: localhost
  username: root
  password: admin
  pool: 10
  reconnect: false
  database: axagenda-jobdependance
  #   socket: /var/run/mysqld/mysqld.sock

calendars:
  adapter: sqlite3
  database: db/calendars.sqlite3
  pool: 5
  timeout: 5000

